/*******************************************************************************
 * SNOWFLAKE SETUP VERIFICATION
 ******************************************************************************/

USE ROLE ACCOUNTADMIN;
USE WAREHOUSE SFE_REACT_AGENT_WH;
USE DATABASE SNOWFLAKE_EXAMPLE;
USE SCHEMA REACT_AGENT_STAGE;

-- Snapshot metadata ----------------------------------------------------------
SHOW WAREHOUSES;
CREATE OR REPLACE TEMP TABLE VERIFY_WH AS
SELECT * FROM TABLE(RESULT_SCAN(LAST_QUERY_ID())) WHERE "name" = 'SFE_REACT_AGENT_WH';

SHOW DATABASES;
CREATE OR REPLACE TEMP TABLE VERIFY_DB AS
SELECT * FROM TABLE(RESULT_SCAN(LAST_QUERY_ID())) WHERE "name" = 'SNOWFLAKE_EXAMPLE';

SHOW SCHEMAS IN DATABASE SNOWFLAKE_EXAMPLE;
CREATE OR REPLACE TEMP TABLE VERIFY_SCHEMA AS
SELECT * FROM TABLE(RESULT_SCAN(LAST_QUERY_ID())) WHERE "name" = 'REACT_AGENT_STAGE';

SHOW STAGES IN SCHEMA REACT_AGENT_STAGE;
CREATE OR REPLACE TEMP TABLE VERIFY_STAGE AS
SELECT * FROM TABLE(RESULT_SCAN(LAST_QUERY_ID())) WHERE "name" = 'DOCUMENTS_STAGE';

CREATE OR REPLACE TEMP TABLE VERIFY_STAGE_INFO AS
SELECT *
FROM INFORMATION_SCHEMA.STAGES
WHERE STAGE_NAME = 'DOCUMENTS_STAGE';

SHOW STREAMS IN SCHEMA REACT_AGENT_STAGE;
CREATE OR REPLACE TEMP TABLE VERIFY_STREAM AS
SELECT "name" AS name FROM TABLE(RESULT_SCAN(LAST_QUERY_ID())) WHERE "name" = 'NEW_DOCUMENTS_STREAM';

SHOW TASKS IN SCHEMA REACT_AGENT_STAGE;
CREATE OR REPLACE TEMP TABLE VERIFY_TASK AS
SELECT "name" AS name, "state" AS state FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()))
WHERE "name" = 'EXTRACT_DOCUMENT_TEXT_TASK';

SHOW USERS;
CREATE OR REPLACE TEMP TABLE VERIFY_USER AS
SELECT * FROM TABLE(RESULT_SCAN(LAST_QUERY_ID())) WHERE "name" = 'SFE_REACT_AGENT_USER';

DESC USER SFE_REACT_AGENT_USER;
CREATE OR REPLACE TEMP TABLE VERIFY_USER_DESC AS
SELECT PROPERTY, VALUE
FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()));

SHOW GRANTS TO USER SFE_REACT_AGENT_USER;
CREATE OR REPLACE TEMP TABLE VERIFY_USER_GRANTS AS
SELECT "granted_on"   AS GRANTED_ON,
       "name"         AS NAME,
       "privilege"    AS PRIVILEGE,
       "grantee_name" AS GRANTEE_NAME
FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()));

SHOW ROLES;
CREATE OR REPLACE TEMP TABLE VERIFY_ROLE AS
SELECT * FROM TABLE(RESULT_SCAN(LAST_QUERY_ID())) WHERE "name" = 'SFE_REACT_AGENT_ROLE';

SHOW GRANTS TO ROLE SFE_REACT_AGENT_ROLE;
CREATE OR REPLACE TEMP TABLE VERIFY_ROLE_GRANTS AS
SELECT "granted_on" AS GRANTED_ON,
       "name"       AS NAME,
       "privilege"  AS PRIVILEGE
FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()));

SHOW TABLES IN SCHEMA REACT_AGENT_STAGE;
CREATE OR REPLACE TEMP TABLE VERIFY_TABLE AS
SELECT * FROM TABLE(RESULT_SCAN(LAST_QUERY_ID())) WHERE "name" = 'DOCUMENT_METADATA';

SHOW AGENTS IN SCHEMA REACT_AGENT_STAGE;
CREATE OR REPLACE TEMP TABLE VERIFY_AGENT AS
SELECT * FROM TABLE(RESULT_SCAN(LAST_QUERY_ID())) WHERE "name" = 'DOCTORCHRIS';

-- Collate PASS/FAIL results ---------------------------------------------------
WITH results AS (
  SELECT 'Warehouse exists' AS check_name,
         CASE WHEN EXISTS (SELECT 1 FROM VERIFY_WH)
              THEN '✅ PASS' ELSE '❌ FAIL' END AS status,
         'SHOW WAREHOUSES' AS detail
  UNION ALL
  SELECT 'Database exists',
         CASE WHEN EXISTS (SELECT 1 FROM VERIFY_DB)
              THEN '✅ PASS' ELSE '❌ FAIL' END,
         'SHOW DATABASES' AS detail
  UNION ALL
  SELECT 'Schema exists',
         CASE WHEN EXISTS (SELECT 1 FROM VERIFY_SCHEMA)
              THEN '✅ PASS' ELSE '❌ FAIL' END,
         'SHOW SCHEMAS IN DATABASE ...' AS detail
  UNION ALL
  SELECT 'Stage exists',
         CASE WHEN EXISTS (SELECT 1 FROM VERIFY_STAGE)
              THEN '✅ PASS' ELSE '❌ FAIL' END,
         'SHOW STAGES IN SCHEMA ...' AS detail
  UNION ALL
  SELECT 'Stage directory enabled',
         CASE WHEN EXISTS (
           SELECT 1
           FROM VERIFY_STAGE_INFO
           WHERE UPPER(CAST(DIRECTORY_ENABLED AS STRING)) = 'TRUE'
         )
              THEN '✅ PASS' ELSE '❌ FAIL' END,
         'DESCRIBE STAGE DOCUMENTS_STAGE' AS detail
  UNION ALL
  SELECT 'Stage is internal (Snowflake-managed SSE)',
         CASE WHEN EXISTS (
           SELECT 1
           FROM VERIFY_STAGE_INFO
           WHERE COALESCE(STAGE_URL, '') = ''
         )
              THEN '✅ PASS' ELSE '❌ FAIL' END,
         'SHOW STAGES LIKE ''DOCUMENTS_STAGE''' AS detail
  UNION ALL
  SELECT 'Stream exists',
         CASE WHEN EXISTS (SELECT 1 FROM VERIFY_STREAM)
              THEN '✅ PASS' ELSE '❌ FAIL' END,
         'SHOW STREAMS IN SCHEMA ...' AS detail
  UNION ALL
  SELECT 'Task exists',
         CASE WHEN EXISTS (SELECT 1 FROM VERIFY_TASK)
              THEN '✅ PASS' ELSE '❌ FAIL' END,
         'SHOW TASKS IN SCHEMA ...' AS detail
  UNION ALL
  SELECT 'Task state = STARTED',
         CASE WHEN EXISTS (SELECT 1 FROM VERIFY_TASK WHERE state = 'started')
              THEN '✅ PASS' ELSE '⚠️ WARN' END,
         'Run ALTER TASK EXTRACT_DOCUMENT_TEXT_TASK RESUME; if WARN' AS detail
  UNION ALL
  SELECT 'Processing procedure exists',
         CASE WHEN EXISTS (
           SELECT 1 FROM INFORMATION_SCHEMA.PROCEDURES
           WHERE PROCEDURE_NAME = 'PROCESS_NEW_DOCUMENTS'
             AND PROCEDURE_SCHEMA = 'REACT_AGENT_STAGE'
         )
              THEN '✅ PASS' ELSE '❌ FAIL' END,
         'INFORMATION_SCHEMA.PROCEDURES' AS detail
  UNION ALL
  SELECT 'Document metadata table exists',
         CASE WHEN EXISTS (SELECT 1 FROM VERIFY_TABLE)
              THEN '✅ PASS' ELSE '❌ FAIL' END,
         'SHOW TABLES IN SCHEMA ...' AS detail
  UNION ALL
  SELECT 'Agent exists',
         CASE WHEN EXISTS (SELECT 1 FROM VERIFY_AGENT)
              THEN '✅ PASS' ELSE '❌ FAIL' END,
         'SHOW AGENTS IN SCHEMA ...' AS detail
  UNION ALL
  SELECT 'Service role exists',
         CASE WHEN EXISTS (SELECT 1 FROM VERIFY_ROLE)
              THEN '✅ PASS' ELSE '❌ FAIL' END,
         'SHOW ROLES' AS detail
  UNION ALL
  SELECT 'Service user exists',
         CASE WHEN EXISTS (SELECT 1 FROM VERIFY_USER)
              THEN '✅ PASS' ELSE '❌ FAIL' END,
         'SHOW USERS' AS detail
  UNION ALL
  SELECT 'Role granted to user',
         CASE WHEN EXISTS (SELECT 1 FROM VERIFY_USER_GRANTS WHERE GRANTED_ON = 'ROLE' AND NAME = 'SFE_REACT_AGENT_ROLE')
              THEN '✅ PASS' ELSE '❌ FAIL' END,
         'GRANT ROLE SFE_REACT_AGENT_ROLE TO USER SFE_REACT_AGENT_USER;' AS detail
  UNION ALL
  SELECT 'RSA public key registered',
         CASE WHEN EXISTS (SELECT 1 FROM VERIFY_USER_DESC WHERE property = 'RSA_PUBLIC_KEY_FP' AND value IS NOT NULL)
              THEN '✅ PASS' ELSE '❌ FAIL' END,
         'ALTER USER SFE_REACT_AGENT_USER SET RSA_PUBLIC_KEY = ...' AS detail
  UNION ALL
  SELECT 'EXECUTE TASK granted to role',
         CASE WHEN EXISTS (SELECT 1 FROM VERIFY_ROLE_GRANTS WHERE PRIVILEGE = 'EXECUTE TASK')
              THEN '✅ PASS' ELSE '❌ FAIL' END,
         'GRANT EXECUTE TASK ON ACCOUNT TO ROLE SFE_REACT_AGENT_ROLE;' AS detail
  UNION ALL
  SELECT 'Stage READ/WRITE granted to role',
         CASE WHEN EXISTS (
           SELECT 1 FROM VERIFY_ROLE_GRANTS
           WHERE PRIVILEGE IN ('READ','WRITE')
             AND GRANTED_ON = 'STAGE'
             AND NAME LIKE '%DOCUMENTS_STAGE%'
         )
              THEN '✅ PASS' ELSE '❌ FAIL' END,
         'GRANT READ, WRITE ON STAGE ... TO ROLE ...' AS detail
  UNION ALL
  SELECT 'Process procedure granted to role',
         CASE WHEN EXISTS (
           SELECT 1 FROM VERIFY_ROLE_GRANTS
           WHERE PRIVILEGE = 'USAGE'
             AND GRANTED_ON = 'PROCEDURE'
             AND NAME ILIKE '%PROCESS_NEW_DOCUMENTS%'
         )
              THEN '✅ PASS' ELSE '⚠️ WARN' END,
         'GRANT USAGE ON PROCEDURE ...PROCESS_NEW_DOCUMENTS() TO ROLE ...' AS detail
)
SELECT check_name, status, detail
FROM results
ORDER BY check_name;

-- Diagnostics -----------------------------------------------------------------
SELECT 'Document count' AS metric, COUNT(*)::STRING AS value
FROM DOCUMENT_METADATA
UNION ALL
SELECT 'Stream has data', SYSTEM$STREAM_HAS_DATA('NEW_DOCUMENTS_STREAM')::STRING;

SELECT FILE_NAME,
       EXTRACTION_TIMESTAMP,
       LEFT(EXTRACTED_TEXT, 120) AS preview
FROM DOCUMENT_METADATA
ORDER BY EXTRACTION_TIMESTAMP DESC
LIMIT 5;
